### ISSUE TITLE
Xcode 7b3 iOS 9b3 breaks VGParallaxHeaderMode.Fill

### ISSUE THREAD

**Issue by jwardle** [stoprocent/VGParallaxHeader#22]
Hi, updating from Xcode 7b2 to Xcode 7b3 breaks the Fill mode. in Xcode 7b3 (Swift based project) the VGParallaxHeader acts like .Center mode and does not fill the header on pull down. Gaps appear above and below the 'header' with the underlying view showing through.

**Comment by stoprocent** [comment]
Sorry for late replay is it still happening ?
Its hard to keep it alive and running without any help right now :(

**Comment by jwardle** [comment]
Not anymore. The b4 update resolved it - must have been a temporary bug. Sorry, forgot to close this!

**Comment by stoprocent** [comment]
No worries thanks for the info!
