### ISSUE TITLE
PopBack content offset issue and header issue

### ISSUE THREAD

**Issue by loloidorap** [stoprocent/VGParallaxHeader#8]
Hi there,

I have some issues when disappearing you can see the content offset changing and when popping back I have to manually scroll the view to see the header else it is sort of hidden. I have tested it on iOS 7 it works fine but iOS 8 seems to do this did you already encountered it ?

Good project though thanks !

**Comment by stoprocent** [comment]
Can you record ur screen and share it here? Im not really getting what is the problem :)

**Comment by loloidorap** [comment]
I have fixed the issue it was about iOS 8 new function estimatedHeightForRowAtIndexPath I completely forgot about it and it was returning the wrong size but this function was used only at pop back not at load, weird anyway issue closed !
